# Generated by Django 2.2.4 on 2021-01-20 01:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.models.control
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000000.0)], verbose_name='Precio unitario')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000)], verbose_name='Cantidad disponible')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción del producto')),
                ('imagen', models.ImageField(upload_to=utils.models.control.path_image, verbose_name='Imagen principal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Productos_Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000000.0)])),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mkt.Productos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000000.0)])),
                ('productos', models.ManyToManyField(through='mkt.Productos_Ventas', to='mkt.Productos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productos_ventas',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mkt.Ventas'),
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('imagen', models.ImageField(upload_to=utils.models.control.path_image)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mkt.Productos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('estatus', models.CharField(choices=[('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='preparando', max_length=50)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='mkt.Ventas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
