# Generated by Django 2.2.4 on 2020-11-24 23:03

import apps.mkt.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000000.0)], verbose_name='Precio unitario')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000)], verbose_name='Cantidad disponible')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción del producto')),
                ('imagen', models.ImageField(upload_to=apps.mkt.models.path_image, verbose_name='Imagen principal')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=apps.mkt.models.path_image)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mkt.Productos')),
            ],
        ),
    ]
