# Generated by Django 2.2.4 on 2021-01-30 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='comision',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000000.0)], verbose_name='Comisión del producto'),
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo_comision',
            field=models.CharField(choices=[('directa', 'Por monto directo'), ('porcentaje', 'Por porcentaje')], max_length=50, null=True, verbose_name='Tipo de comisión'),
        ),
    ]
