# Generated by Django 2.2.4 on 2021-03-02 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('mkt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='usuario',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productos_ventas',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mkt.Productos'),
        ),
        migrations.AddField(
            model_name='productos_ventas',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdt_ventas', to='mkt.Ventas'),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mkt.Productos'),
        ),
        migrations.AddField(
            model_name='envios',
            name='direccion',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='users.Direcciones'),
        ),
        migrations.AddField(
            model_name='envios',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='mkt.Ventas'),
        ),
    ]
