# Generated by Django 2.2.4 on 2021-03-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0002_auto_20210302_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
