# Generated by Django 2.2.4 on 2021-01-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0003_auto_20210130_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='folio',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='folio',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='folio',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
