# Generated by Django 2.2.4 on 2021-03-04 19:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0003_auto_20210303_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=25, null=True, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_cat', to='mkt.Categorias')),
            ],
            options={
                'ordering': ['-fecha_reg'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='categorias',
            field=models.ManyToManyField(related_name='cat_pdt', to='mkt.Categorias'),
        ),
    ]
