# Generated by Django 2.2.4 on 2021-01-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0004_auto_20210130_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='folio',
            field=models.CharField(editable=False, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='folio',
            field=models.CharField(editable=False, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='folio',
            field=models.CharField(editable=False, max_length=25, null=True, unique=True),
        ),
    ]
