# Generated by Django 2.2.4 on 2021-04-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0005_auto_20210304_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_cat', to='mkt.Categorias'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='estatus',
            field=models.CharField(choices=[('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='preparando', max_length=50),
        ),
    ]
