# Generated by Django 2.2.4 on 2021-02-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0005_auto_20210130_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_ventas',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdt_ventas', to='mkt.Productos'),
        ),
    ]
