# Generated by Django 2.2.4 on 2021-02-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0006_auto_20210205_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos_ventas',
            old_name='cantidad',
            new_name='cantidad_final',
        ),
        migrations.RenameField(
            model_name='productos_ventas',
            old_name='precio',
            new_name='precio_final',
        ),
    ]
