# Generated by Django 2.2.4 on 2021-02-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0007_auto_20210205_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos_ventas',
            old_name='cantidad_final',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='productos_ventas',
            old_name='precio_final',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='productos_ventas',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mkt.Productos'),
        ),
        migrations.AlterField(
            model_name='productos_ventas',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdt_ventas', to='mkt.Ventas'),
        ),
    ]
