# Generated by Django 2.2.4 on 2021-02-09 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_direcciones_alias'),
        ('mkt', '0009_auto_20210205_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='direccion',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='users.Direcciones'),
        ),
        migrations.AddField(
            model_name='envios',
            name='direccion_txt',
            field=models.CharField(editable=False, max_length=300, null=True),
        ),
    ]
