# Generated by Django 2.2.4 on 2021-02-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0010_auto_20210209_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='direccion_txt',
            field=models.TextField(editable=False, null=True),
        ),
    ]
