# Generated by Django 2.2.4 on 2021-02-12 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0011_auto_20210209_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envios',
            options={'ordering': ['-fecha_reg']},
        ),
        migrations.AlterModelOptions(
            name='imagenes',
            options={'ordering': ['-fecha_reg']},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['-fecha_reg']},
        ),
        migrations.AlterModelOptions(
            name='productos_ventas',
            options={'ordering': ['-fecha_reg']},
        ),
        migrations.AlterField(
            model_name='envios',
            name='direccion',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='users.Direcciones'),
        ),
    ]
