# Generated by Django 2.2.4 on 2021-02-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0012_auto_20210211_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='id_payment',
            field=models.CharField(editable=False, max_length=30, null=True),
        ),
    ]
