# Generated by Django 2.2.4 on 2021-02-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0013_ventas_id_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='id_payment',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
