# Generated by Django 2.2.4 on 2021-03-02 18:56

import apps.users.mixins.email_confirmation
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Ingrese un número de telefono correcto')], verbose_name='Número de teléfono')),
                ('is_confirmed', models.BooleanField(default=False, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-is_superuser', 'date_joined'],
            },
            bases=(apps.users.mixins.email_confirmation.SendEmail, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('alias', models.CharField(max_length=100, null=True, verbose_name='Alias de la dirección')),
                ('calle', models.CharField(max_length=100, verbose_name='Nombre de la calle')),
                ('no_calle', models.CharField(default='s/n', max_length=6, verbose_name='Número exterior')),
                ('no_interior', models.CharField(default='s/n', max_length=6, verbose_name='Número interior')),
                ('colonia', models.CharField(max_length=100, verbose_name='Nombre de la colonia')),
                ('codigo_postal', models.CharField(max_length=5, null=True, verbose_name='Código postal')),
                ('referencias', models.CharField(max_length=200, verbose_name='Referencias para ubicar el lugar')),
                ('instrucciones', models.CharField(max_length=200, verbose_name='Instrucciones de entrega')),
                ('default', models.BooleanField(default=False, verbose_name='Usar esta dirección como predeterminada')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_reg'],
                'abstract': False,
            },
        ),
    ]
