# Generated by Django 2.2.4 on 2021-01-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciones',
            name='folio',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
