# Generated by Django 2.2.4 on 2021-02-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210130_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciones',
            name='no_interior',
            field=models.CharField(default='s/n', max_length=6, verbose_name='Número interior'),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='no_calle',
            field=models.CharField(default='s/n', max_length=6, verbose_name='Número exterior'),
        ),
    ]
