# Generated by Django 2.2.4 on 2021-02-09 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210202_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direcciones',
            name='folio',
        ),
        migrations.AddField(
            model_name='direcciones',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Usar esta dirección como predeterminada'),
        ),
        migrations.AddField(
            model_name='direcciones',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
