# Generated by Django 2.2.4 on 2021-02-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210209_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciones',
            name='codigo_postal',
            field=models.CharField(max_length=5, null=True, verbose_name='Código postal'),
        ),
    ]
