# Generated by Django 2.2.4 on 2021-02-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_direcciones_codigo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciones',
            name='alias',
            field=models.CharField(max_length=100, null=True, verbose_name='Alias de la dirección'),
        ),
    ]
