# Generated by Django 2.2.4 on 2021-02-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_direcciones_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direcciones',
            options={'ordering': ['-fecha_reg']},
        ),
    ]
