# Generated by Django 2.2.4 on 2021-02-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210211_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_confirmed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
