# Generated by Django 2.2.4 on 2021-02-25 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usuarios_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Ingrese un número de telefono correcto')], verbose_name='Número de teléfono'),
        ),
    ]
