# Generated by Django 2.2.4 on 2021-02-16 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=25, null=True, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('id_customer', models.CharField(editable=False, max_length=50)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='customer_payment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_reg'],
                'abstract': False,
            },
        ),
    ]
