# Generated by Django 2.2.4 on 2021-03-02 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='customer_payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
